### ISSUE TITLE
KeyError: '6' 当我想要测试自己的数据集时，遇到了keyerror6的问题

### ISSUE THREAD

**Issue by xuptacm** [THUDM/GATNE#83]
{'epoch': 0, 'iter': 0, 'avg_loss': 19.13713836669922, 'loss': 19.137138}
{'epoch': 0, 'iter': 5000, 'avg_loss': 9.393543103258029, 'loss': 5.517972}
epoch 0: 100%|| 7767/7767 [05:38<00:00, 22.95it/s]
Traceback (most recent call last):
  File "src/main.py", line 226, in <module>
    average_auc, average_f1, average_pr = train_model(training_data_by_type, feature_dic, log_name + '_' + time.strftime('%Y-%m-%d %H-%M-%S',time.localtime(time.time())))
  File "src/main.py", line 181, in train_model
    tmp_auc, tmp_f1, tmp_pr = evaluate(final_model[edge_types[i]], valid_true_data_by_edge[edge_types[i]], valid_false_data_by_edge[edge_types[i]])
KeyError: '6'

**Comment by cenyk1230** [comment]
Hi @xuptacm,

This issue is similar to the #67 issue. Please first check whether it solves your problem.
